apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXMxMjM=
  PAYMENT_API_KEY: cGF5bWVudC1hcGkta2V5LTEyMw==
  EMAIL_API_KEY: ZW1haWwtYXBpLWtleS0xMjM=