apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        command: {{- toYaml .Values.redis.command | nindent 8 }}
        ports:
        - containerPort: {{ .Values.redis.port }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.redis.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: {{ .Values.redis.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: redis-cart
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}