apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.services.productcatalogservice.replicas }}
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: server
        image: {{ .Values.global.imageRegistry }}/{{ .Values.services.productcatalogservice.image }}:{{ .Values.global.imageTag }}
        ports:
        - containerPort: {{ .Values.services.productcatalogservice.containerPort }}
        envFrom:
        - configMapRef:
            name: microservices-config
        resources:
          {{- toYaml .Values.services.productcatalogservice.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.services.productcatalogservice.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: {{ .Values.services.productcatalogservice.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: productcatalogservice
  ports:
  - port: {{ .Values.services.productcatalogservice.servicePort }}
    targetPort: {{ .Values.services.productcatalogservice.containerPort }}