apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.services.emailservice.replicas }}
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: server
        image: {{ .Values.global.imageRegistry }}/{{ .Values.services.emailservice.image }}:{{ .Values.global.imageTag }}
        ports:
        - containerPort: {{ .Values.services.emailservice.containerPort }}
        envFrom:
        - configMapRef:
            name: microservices-config
        env:
        - name: EMAIL_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.services.emailservice.env.EMAIL_API_KEY.secretKeyRef.name }}
              key: {{ .Values.services.emailservice.env.EMAIL_API_KEY.secretKeyRef.key }}
        resources:
          {{- toYaml .Values.services.emailservice.resources | nindent 10 }}
        livenessProbe:
          grpc:
            port: {{ .Values.services.emailservice.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: {{ .Values.services.emailservice.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: emailservice
  ports:
  - port: {{ .Values.services.emailservice.servicePort }}
    targetPort: {{ .Values.services.emailservice.containerPort }}