apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.services.cartservice.replicas }}
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: server
        image: {{ .Values.global.imageRegistry }}/{{ .Values.services.cartservice.image }}:{{ .Values.global.imageTag }}
        ports:
        - containerPort: {{ .Values.services.cartservice.containerPort }}
        envFrom:
        - configMapRef:
            name: microservices-config
        env:
        - name: REDIS_ADDR
          value: {{ .Values.services.cartservice.env.REDIS_ADDR | quote }}
        resources:
          {{- toYaml .Values.services.cartservice.resources | nindent 10 }}
        livenessProbe:
          grpc:
            port: {{ .Values.services.cartservice.containerPort }}
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: {{ .Values.services.cartservice.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: cartservice
  ports:
  - port: {{ .Values.services.cartservice.servicePort }}
    targetPort: {{ .Values.services.cartservice.containerPort }}