apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
data:
  # Redis password (base64 encoded "redis123")
  REDIS_PASSWORD: cmVkaXMxMjM=
  # Dummy API keys (base64 encoded)
  PAYMENT_API_KEY: cGF5bWVudC1hcGkta2V5LTEyMw==
  EMAIL_API_KEY: ZW1haWwtYXBpLWtleS0xMjM=