apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: server
        image: matthewntsiful/microservices-currencyservice:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: microservices-config
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: microservices
spec:
  selector:
    app: currencyservice
  ports:
  - port: 7000
    targetPort: 8080