apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: server
        image: matthewntsiful/microservices-checkoutservice:latest
        ports:
        - containerPort: 5050
        envFrom:
        - configMapRef:
            name: microservices-config
        env:
        - name: PORT
          value: "5050"
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  selector:
    app: checkoutservice
  ports:
  - port: 5050
    targetPort: 5050