name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'microservices-demo/src/**'
      - 'k8s-manifests/**'
      - '.github/workflows/ci-cd.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [frontend, cartservice, checkoutservice, productcatalogservice, currencyservice, paymentservice, shippingservice, emailservice, recommendationservice, adservice]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./microservices-demo/src/${{ matrix.service }}${{ matrix.service == 'cartservice' && '/src' || '' }}
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/microservices-${{ matrix.service }}:${{ env.IMAGE_TAG }}

  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        service: [frontend, cartservice, checkoutservice, productcatalogservice, currencyservice, paymentservice, shippingservice, emailservice, recommendationservice, adservice]
    steps:
    - uses: actions/checkout@v4
    
    - name: Scan image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ github.repository }}/microservices-${{ matrix.service }}:${{ env.IMAGE_TAG }}
        format: 'table'
        severity: 'CRITICAL,HIGH'

  deploy:
    name: Deploy to Kind
    runs-on: self-hosted
    needs: [build, scan]
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Update manifests
      run: |
        find k8s-manifests -name '*.yaml' -exec sed -i '' 's|matthewntsiful/microservices-|${{ env.REGISTRY }}/${{ github.repository }}/microservices-|g' {} \;
        find k8s-manifests -name '*.yaml' -exec sed -i '' 's|:latest|:${{ env.IMAGE_TAG }}|g' {} \;
    
    - name: Deploy manifests
      run: |
        find k8s-manifests -name '*.yaml' ! -name '14-ingress.yaml' -exec kubectl apply -f {} \;
    
    - name: Update deployment images (zero downtime)
      run: |
        kubectl set image deployment/frontend frontend=${{ env.REGISTRY }}/${{ github.repository }}/microservices-frontend:${{ env.IMAGE_TAG }} -n microservices
        kubectl set image deployment/cartservice server=${{ env.REGISTRY }}/${{ github.repository }}/microservices-cartservice:${{ env.IMAGE_TAG }} -n microservices
        kubectl set image deployment/checkoutservice server=${{ env.REGISTRY }}/${{ github.repository }}/microservices-checkoutservice:${{ env.IMAGE_TAG }} -n microservices
        kubectl set image deployment/productcatalogservice server=${{ env.REGISTRY }}/${{ github.repository }}/microservices-productcatalogservice:${{ env.IMAGE_TAG }} -n microservices
        kubectl set image deployment/currencyservice server=${{ env.REGISTRY }}/${{ github.repository }}/microservices-currencyservice:${{ env.IMAGE_TAG }} -n microservices
        kubectl set image deployment/paymentservice server=${{ env.REGISTRY }}/${{ github.repository }}/microservices-paymentservice:${{ env.IMAGE_TAG }} -n microservices
        kubectl set image deployment/shippingservice server=${{ env.REGISTRY }}/${{ github.repository }}/microservices-shippingservice:${{ env.IMAGE_TAG }} -n microservices
        kubectl set image deployment/emailservice server=${{ env.REGISTRY }}/${{ github.repository }}/microservices-emailservice:${{ env.IMAGE_TAG }} -n microservices
        kubectl set image deployment/recommendationservice server=${{ env.REGISTRY }}/${{ github.repository }}/microservices-recommendationservice:${{ env.IMAGE_TAG }} -n microservices
        kubectl set image deployment/adservice server=${{ env.REGISTRY }}/${{ github.repository }}/microservices-adservice:${{ env.IMAGE_TAG }} -n microservices
    
    - name: Deploy ingress
      run: |
        kubectl delete validatingwebhookconfiguration ingress-nginx-admission || true
        kubectl apply -f k8s-manifests/14-ingress.yaml -n microservices
    
    - name: Wait for rollout
      run: |
        for deployment in $(kubectl get deployments -n microservices -o name | grep -v redis); do kubectl rollout status $deployment -n microservices --timeout=300s; done
        echo "✅ Zero-downtime deployment completed!"

        ###