name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      image_tag:
        description: 'Image tag to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure kubectl
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    
    - name: Update image tags
      run: |
        sed -i 's/:latest/:${{ github.event.inputs.image_tag }}/g' k8s-manifests/*.yaml
    
    - name: Deploy to ${{ github.event.inputs.environment }}
      run: |
        NAMESPACE=${{ github.event.inputs.environment == 'production' && 'microservices' || 'microservices-staging' }}
        kubectl apply -f k8s-manifests/ -n $NAMESPACE
        kubectl rollout status deployment --all -n $NAMESPACE --timeout=600s
    
    - name: Verify deployment
      run: |
        NAMESPACE=${{ github.event.inputs.environment == 'production' && 'microservices' || 'microservices-staging' }}
        kubectl get pods -n $NAMESPACE
        kubectl get hpa -n $NAMESPACE