name: Security Scan

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:

jobs:
  container-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, cartservice, checkoutservice, productcatalogservice, currencyservice, paymentservice, shippingservice, emailservice, recommendationservice, adservice]
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'matthewntsiful/microservices-${{ matrix.service }}:latest'
        format: 'sarif'
        output: 'trivy-${{ matrix.service }}.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-${{ matrix.service }}.sarif'

  k8s-security-scan:
    name: Kubernetes Security Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Kubesec scan
      run: |
        curl -sSX POST --data-binary @k8s-manifests/13-frontend.yaml https://v2.kubesec.io/scan
        curl -sSX POST --data-binary @k8s-manifests/11-cartservice.yaml https://v2.kubesec.io/scan